project:
  type: website

website:
  title: "Stan PMx"
  google-analytics: "G-0B50RXDB1S"
  site-url: "https://stanpmx.github.io"
  announcement: 
    content: "Stay tuned for a major update and come to StanBio Connect on May 30, 2025!" 
    position: below-navbar 
  page-footer:
    right: "&copy; GNU GPL v3.0"
    left: 
      - icon: github
        href: https://github.com/StanPMx/stanpmx.github.io
        # text: "https://github.com/BayesPMx/stanpmx.github.io"
      - icon: globe
        href: https://stanpmx.github.io
        # text: "https://stanpmx.github.io"
      - icon: github
        href: https://github.com/cbdavis33/stanpmx-library
        text: "StanPMx Library"
    background: "#AAB1B3"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     # - about.qmd
  sidebar: 
    search: true
    pinned: true
    logo: "Images/stanpmx_logo.png"
    contents:
      - text: "Home"
        file: index.qmd
      # - text: "About"
      #   file: about.qmd

format:
  html:
    page-layout: article
    respect-user-color-scheme: true
    theme:
      light: [sandstone, Aesthetics/theme-light.scss]
      dark: [sandstone, Aesthetics/theme-dark.scss]
    css: Aesthetics/quarto_styles.css
    toc: true

editor: visual
